/*
  # Sentinel GRC v3.0 - AI Chat and Document Embeddings

  ## Summary
  Creates AI-powered features for Sentinel:
  - AI chat sessions for The Oracle assistant
  - Chat message history with citations
  - Vector embeddings for semantic search (RAG)

  ## New Tables
    - ai_chat_sessions - Chat session management
    - ai_chat_messages - Individual chat messages
    - document_embeddings - Vector embeddings for document search

  ## Security
    - RLS enabled on all tables
    - Users can only access their own chat sessions
    - Embeddings are readable by all authenticated users
*/

-- Enable vector extension for AI embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- AI Chat Sessions
CREATE TABLE IF NOT EXISTS ai_chat_sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255),
    created_by UUID,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    is_archived BOOLEAN DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_ai_chat_sessions_created_by ON ai_chat_sessions(created_by);

ALTER TABLE ai_chat_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own chat sessions"
    ON ai_chat_sessions FOR SELECT TO authenticated USING (auth.uid() = created_by);

CREATE POLICY "Users can insert own chat sessions"
    ON ai_chat_sessions FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by);

CREATE POLICY "Users can update own chat sessions"
    ON ai_chat_sessions FOR UPDATE TO authenticated
    USING (auth.uid() = created_by)
    WITH CHECK (auth.uid() = created_by);

-- AI Chat Messages
CREATE TABLE IF NOT EXISTS ai_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID,
    role VARCHAR(20) CHECK (role IN ('USER', 'ASSISTANT', 'SYSTEM')),
    content TEXT NOT NULL,
    citations_json JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_chat_messages_session_id ON ai_chat_messages(session_id);

ALTER TABLE ai_chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own chat messages"
    ON ai_chat_messages FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM ai_chat_sessions
            WHERE ai_chat_sessions.session_id = ai_chat_messages.session_id
            AND ai_chat_sessions.created_by = auth.uid()
        )
    );

CREATE POLICY "Users can insert own chat messages"
    ON ai_chat_messages FOR INSERT TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM ai_chat_sessions
            WHERE ai_chat_sessions.session_id = ai_chat_messages.session_id
            AND ai_chat_sessions.created_by = auth.uid()
        )
    );

-- Document Embeddings
CREATE TABLE IF NOT EXISTS document_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(50) NOT NULL,
    source_id UUID,
    content_chunk TEXT NOT NULL,
    embedding vector(1536),
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_document_embeddings_vector
    ON document_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE INDEX IF NOT EXISTS idx_document_embeddings_source ON document_embeddings(source_type, source_id);

ALTER TABLE document_embeddings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read embeddings"
    ON document_embeddings FOR SELECT TO authenticated USING (true);

-- Helper Function for Vector Similarity Search
CREATE OR REPLACE FUNCTION search_similar_documents(
    query_embedding vector(1536),
    match_threshold float DEFAULT 0.7,
    match_count int DEFAULT 5
)
RETURNS TABLE (
    id bigint,
    source_type varchar,
    content_chunk text,
    similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        document_embeddings.id,
        document_embeddings.source_type,
        document_embeddings.content_chunk,
        1 - (document_embeddings.embedding <=> query_embedding) as similarity
    FROM document_embeddings
    WHERE 1 - (document_embeddings.embedding <=> query_embedding) > match_threshold
    ORDER BY document_embeddings.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;
