/*
  # Create CCM & Probes Module Schema + Seed Data

  1. New Tables
    - `data_sources` - External data source registry for continuous monitoring
      - `id` (uuid, PK), `name`, `source_type`, `status`, `last_sync_at`, `record_count`, `metadata`, `created_at`
    - `ccm_transactions` - Ingested transactions for anomaly detection
      - `id` (uuid, PK), `source_system`, `transaction_date`, `amount`, `currency`, `user_id`, `beneficiary`, `transaction_type`, `metadata`, `created_at`
    - `ccm_alerts` - Alerts generated by CCM rules engine
      - `id` (uuid, PK), `rule_triggered`, `risk_score`, `severity`, `title`, `description`, `evidence_data`, `related_entity_id`, `status`, `assigned_to`, `resolved_at`, `metadata`, `created_at`, `updated_at`
    - `probes` - Sentinel Probe definitions (automated audit checks)
      - `id` (uuid, PK), `tenant_id`, `title`, `description`, `query_type`, `query_payload`, `schedule_cron`, `risk_threshold`, `target_control_id`, `is_active`, `last_run_at`, `last_result_status`, `category`, `severity`, `created_by`, `created_at`, `updated_at`
    - `probe_runs` - Execution history for probes
      - `id` (uuid, PK), `tenant_id`, `probe_id`, `items_found`, `execution_time_ms`, `status`, `run_metadata`, `started_at`, `completed_at`, `created_at`
    - `shadow_transactions` - Synthetic test transactions from Chaos Lab
      - `id` (uuid, PK), `amount`, `currency`, `scenario`, `is_synthetic`, `blocked_by_core`, `source_account`, `target_account`, `injected_by`, `batch_id`, `created_at`

  2. Security
    - RLS enabled on all tables
    - Permissive anon policies for demo environment

  3. Seed Data
    - 3 data sources, 50 CCM transactions (with Benford anomalies), 8 alerts, 5 probes, 10 probe runs
*/

-- data_sources
CREATE TABLE IF NOT EXISTS data_sources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  source_type text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'OFFLINE', 'MAINTENANCE')),
  last_sync_at timestamptz DEFAULT now(),
  record_count integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE data_sources ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_data_sources_select" ON data_sources FOR SELECT TO anon USING (true);
CREATE POLICY "anon_data_sources_insert" ON data_sources FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "anon_data_sources_update" ON data_sources FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon_data_sources_delete" ON data_sources FOR DELETE TO anon USING (true);

-- ccm_transactions
CREATE TABLE IF NOT EXISTS ccm_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_system text NOT NULL DEFAULT '',
  transaction_date timestamptz NOT NULL DEFAULT now(),
  amount numeric(18,2) NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'TRY',
  user_id text NOT NULL DEFAULT '',
  beneficiary text NOT NULL DEFAULT '',
  transaction_type text NOT NULL DEFAULT '',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE ccm_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_ccm_tx_select" ON ccm_transactions FOR SELECT TO anon USING (true);
CREATE POLICY "anon_ccm_tx_insert" ON ccm_transactions FOR INSERT TO anon WITH CHECK (true);

-- ccm_alerts
CREATE TABLE IF NOT EXISTS ccm_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rule_triggered text NOT NULL DEFAULT '',
  risk_score numeric(5,2) NOT NULL DEFAULT 0,
  severity text NOT NULL DEFAULT 'MEDIUM' CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  title text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  evidence_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  related_entity_id text,
  status text NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'INVESTIGATING', 'CONFIRMED', 'DISMISSED')),
  assigned_to text,
  resolved_at timestamptz,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE ccm_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_ccm_alerts_select" ON ccm_alerts FOR SELECT TO anon USING (true);
CREATE POLICY "anon_ccm_alerts_insert" ON ccm_alerts FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "anon_ccm_alerts_update" ON ccm_alerts FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon_ccm_alerts_delete" ON ccm_alerts FOR DELETE TO anon USING (true);

-- probes
CREATE TABLE IF NOT EXISTS probes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '11111111-1111-1111-1111-111111111111',
  title text NOT NULL,
  description text DEFAULT '',
  query_type text NOT NULL DEFAULT 'SQL' CHECK (query_type IN ('SQL', 'API', 'WEBHOOK')),
  query_payload text NOT NULL DEFAULT '',
  schedule_cron text,
  risk_threshold numeric(5,2) NOT NULL DEFAULT 50,
  target_control_id text,
  is_active boolean NOT NULL DEFAULT true,
  last_run_at timestamptz,
  last_result_status text CHECK (last_result_status IS NULL OR last_result_status IN ('PASS', 'FAIL', 'ERROR')),
  category text NOT NULL DEFAULT 'OPS' CHECK (category IN ('FRAUD', 'OPS', 'COMPLIANCE')),
  severity text NOT NULL DEFAULT 'MEDIUM' CHECK (severity IN ('HIGH', 'MEDIUM', 'LOW')),
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE probes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_probes_select" ON probes FOR SELECT TO anon USING (true);
CREATE POLICY "anon_probes_insert" ON probes FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "anon_probes_update" ON probes FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon_probes_delete" ON probes FOR DELETE TO anon USING (true);

-- probe_runs
CREATE TABLE IF NOT EXISTS probe_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '11111111-1111-1111-1111-111111111111',
  probe_id uuid NOT NULL REFERENCES probes(id) ON DELETE CASCADE,
  items_found integer NOT NULL DEFAULT 0,
  execution_time_ms integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'PASS' CHECK (status IN ('PASS', 'FAIL', 'ERROR')),
  run_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE probe_runs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_probe_runs_select" ON probe_runs FOR SELECT TO anon USING (true);
CREATE POLICY "anon_probe_runs_insert" ON probe_runs FOR INSERT TO anon WITH CHECK (true);

-- shadow_transactions
CREATE TABLE IF NOT EXISTS shadow_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  amount numeric(18,2) NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'TRY',
  scenario text NOT NULL DEFAULT '' CHECK (scenario IN ('SMURFING_TEST', 'ROUND_TRIP_TEST', 'GHOST_PAYROLL_TEST', 'BENFORD_MANIPULATION', '')),
  is_synthetic boolean NOT NULL DEFAULT true,
  blocked_by_core boolean NOT NULL DEFAULT false,
  source_account text NOT NULL DEFAULT '',
  target_account text NOT NULL DEFAULT '',
  injected_by text NOT NULL DEFAULT '',
  batch_id text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE shadow_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_shadow_tx_select" ON shadow_transactions FOR SELECT TO anon USING (true);
CREATE POLICY "anon_shadow_tx_insert" ON shadow_transactions FOR INSERT TO anon WITH CHECK (true);
