import type { BankGoal, AuditObjective, StrategyAlignment } from '../model/types';

const MOCK_TENANT_ID = '11111111-1111-1111-1111-111111111111';

export const MOCK_BANK_GOALS: BankGoal[] = [
  {
    id: 'goal-001',
    tenant_id: MOCK_TENANT_ID,
    title: 'Dijital Kanallarda %25 Büyüme',
    description: 'Mobil ve internet bankacılığı kullanıcı sayısını artırarak dijital işlem hacminde %25 büyüme sağlamak.',
    period_year: 2026,
    weight: 90,
    category: 'GROWTH',
    owner_executive: 'Dijital Bankacılık Genel Müdür Yardımcısı',
    created_at: '2026-01-05T10:00:00Z',
    updated_at: '2026-01-05T10:00:00Z',
  },
  {
    id: 'goal-002',
    tenant_id: MOCK_TENANT_ID,
    title: 'Operasyonel Verimlilik İyileştirmesi',
    description: 'Süreç otomasyonu ve dijitalleşme ile operasyonel maliyetlerde %15 azaltma hedefi.',
    period_year: 2026,
    weight: 80,
    category: 'EFFICIENCY',
    owner_executive: 'Operasyonlar Genel Müdür Yardımcısı',
    created_at: '2026-01-05T10:15:00Z',
    updated_at: '2026-01-05T10:15:00Z',
  },
  {
    id: 'goal-003',
    tenant_id: MOCK_TENANT_ID,
    title: 'Siber Güvenlik Altyapısının Güçlendirilmesi',
    description: 'Siber saldırılara karşı koruma sistemlerinin modernizasyonu ve olay müdahale kapasitesinin artırılması.',
    period_year: 2026,
    weight: 95,
    category: 'COMPLIANCE',
    owner_executive: 'BT ve Bilgi Güvenliği Genel Müdür Yardımcısı',
    created_at: '2026-01-05T10:30:00Z',
    updated_at: '2026-01-05T10:30:00Z',
  },
  {
    id: 'goal-004',
    tenant_id: MOCK_TENANT_ID,
    title: 'KOBİ Kredileri Portföyünde %20 Artış',
    description: 'Küçük ve orta ölçekli işletmelere yönelik kredi ürünlerinin geliştirilmesi ve pazar payının artırılması.',
    period_year: 2026,
    weight: 85,
    category: 'GROWTH',
    owner_executive: 'Krediler Genel Müdür Yardımcısı',
    created_at: '2026-01-05T10:45:00Z',
    updated_at: '2026-01-05T10:45:00Z',
  },
  {
    id: 'goal-005',
    tenant_id: MOCK_TENANT_ID,
    title: 'Yapay Zeka Destekli Müşteri Deneyimi',
    description: 'AI tabanlı chatbot ve kişiselleştirilmiş ürün önerileri ile müşteri memnuniyetini %30 artırmak.',
    period_year: 2026,
    weight: 75,
    category: 'INNOVATION',
    owner_executive: 'Müşteri Deneyimi Genel Müdür Yardımcısı',
    created_at: '2026-01-05T11:00:00Z',
    updated_at: '2026-01-05T11:00:00Z',
  },
  {
    id: 'goal-006',
    tenant_id: MOCK_TENANT_ID,
    title: 'Sürdürülebilir Finansman Portföyü',
    description: 'Yeşil finans ve ESG uyumlu yatırım ürünlerinin toplam portföy içindeki payının %10\'a çıkarılması.',
    period_year: 2026,
    weight: 70,
    category: 'COMPLIANCE',
    owner_executive: 'Kurumsal Yönetim ve Sürdürülebilirlik Müdürü',
    created_at: '2026-01-05T11:15:00Z',
    updated_at: '2026-01-05T11:15:00Z',
  },
];

export const MOCK_AUDIT_OBJECTIVES: AuditObjective[] = [
  {
    id: 'obj-001',
    tenant_id: MOCK_TENANT_ID,
    title: 'Dijital Dönüşüm Risklerinin Değerlendirilmesi',
    description: 'Dijital bankacılık altyapısı, siber güvenlik kontrolleri ve teknoloji risk yönetiminin güvence altına alınması.',
    period_year: 2026,
    category: 'ASSURANCE',
    created_at: '2026-01-06T09:00:00Z',
    updated_at: '2026-01-06T09:00:00Z',
  },
  {
    id: 'obj-002',
    tenant_id: MOCK_TENANT_ID,
    title: 'Süreç Optimizasyonu Danışmanlığı',
    description: 'Operasyonel süreçlerin iyileştirilmesi için yönetim kuruluna danışmanlık hizmeti sunulması.',
    period_year: 2026,
    category: 'ADVISORY',
    created_at: '2026-01-06T09:15:00Z',
    updated_at: '2026-01-06T09:15:00Z',
  },
  {
    id: 'obj-003',
    tenant_id: MOCK_TENANT_ID,
    title: 'Siber Güvenlik Olgunluk Değerlendirmesi',
    description: 'BDDK ve ISO 27001 standartlarına uyum dahil siber güvenlik altyapısının test edilmesi.',
    period_year: 2026,
    category: 'ASSURANCE',
    created_at: '2026-01-06T09:30:00Z',
    updated_at: '2026-01-06T09:30:00Z',
  },
  {
    id: 'obj-004',
    tenant_id: MOCK_TENANT_ID,
    title: 'Kredi Riski Yönetim Sistemlerinin Denetimi',
    description: 'Kredi tahsis süreçleri, risk sınıflandırma modelleri ve karşılık ayrımlarının etkinliğinin değerlendirilmesi.',
    period_year: 2026,
    category: 'RISK_MANAGEMENT',
    created_at: '2026-01-06T09:45:00Z',
    updated_at: '2026-01-06T09:45:00Z',
  },
  {
    id: 'obj-005',
    tenant_id: MOCK_TENANT_ID,
    title: 'Yapay Zeka ve Veri Analitiği Governance',
    description: 'AI/ML modellerinin etik kullanımı, veri kalitesi ve algoritmik şeffaflığın güvence altına alınması.',
    period_year: 2026,
    category: 'GOVERNANCE',
    created_at: '2026-01-06T10:00:00Z',
    updated_at: '2026-01-06T10:00:00Z',
  },
  {
    id: 'obj-006',
    tenant_id: MOCK_TENANT_ID,
    title: 'ESG Raporlama ve Uyum Denetimi',
    description: 'Sürdürülebilir finans düzenlemelerine uyum ve ESG raporlama kalitesinin değerlendirilmesi.',
    period_year: 2026,
    category: 'ASSURANCE',
    created_at: '2026-01-06T10:15:00Z',
    updated_at: '2026-01-06T10:15:00Z',
  },
  {
    id: 'obj-007',
    tenant_id: MOCK_TENANT_ID,
    title: 'İç Kontrol Sistemlerinin Etkinlik Analizi',
    description: '3 Savunma Hattı modelinin işleyişi ve kontrol ortamının sürekli iyileştirilmesi.',
    period_year: 2026,
    category: 'GOVERNANCE',
    created_at: '2026-01-06T10:30:00Z',
    updated_at: '2026-01-06T10:30:00Z',
  },
];

export const MOCK_ALIGNMENTS: StrategyAlignment[] = [
  {
    id: 'align-001',
    tenant_id: MOCK_TENANT_ID,
    bank_goal_id: 'goal-001',
    audit_objective_id: 'obj-001',
    relevance_score: 0.95,
    rationale: 'Dijital büyüme hedefi için teknoloji altyapısının güvenliğinin ve güvenilirliğinin sağlanması kritik öneme sahiptir.',
    created_at: '2026-01-07T14:00:00Z',
    updated_at: '2026-01-07T14:00:00Z',
  },
  {
    id: 'align-002',
    tenant_id: MOCK_TENANT_ID,
    bank_goal_id: 'goal-002',
    audit_objective_id: 'obj-002',
    relevance_score: 0.90,
    rationale: 'Operasyonel verimlilik hedefi için süreç analizi ve iyileştirme önerilerinin danışmanlık desteği gereklidir.',
    created_at: '2026-01-07T14:15:00Z',
    updated_at: '2026-01-07T14:15:00Z',
  },
  {
    id: 'align-003',
    tenant_id: MOCK_TENANT_ID,
    bank_goal_id: 'goal-003',
    audit_objective_id: 'obj-003',
    relevance_score: 1.0,
    rationale: 'Siber güvenlik güçlendirme hedefi ile siber güvenlik denetimi tam uyum içindedir.',
    created_at: '2026-01-07T14:30:00Z',
    updated_at: '2026-01-07T14:30:00Z',
  },
  {
    id: 'align-004',
    tenant_id: MOCK_TENANT_ID,
    bank_goal_id: 'goal-004',
    audit_objective_id: 'obj-004',
    relevance_score: 0.85,
    rationale: 'KOBİ kredileri büyüme hedefi için kredi riski yönetim sistemlerinin etkinliğinin doğrulanması gerekir.',
    created_at: '2026-01-07T14:45:00Z',
    updated_at: '2026-01-07T14:45:00Z',
  },
  {
    id: 'align-005',
    tenant_id: MOCK_TENANT_ID,
    bank_goal_id: 'goal-005',
    audit_objective_id: 'obj-005',
    relevance_score: 0.90,
    rationale: 'AI tabanlı müşteri deneyimi hedefi için yapay zeka yönetişimi ve etik kullanımının güvence altına alınması şarttır.',
    created_at: '2026-01-07T15:00:00Z',
    updated_at: '2026-01-07T15:00:00Z',
  },
  {
    id: 'align-006',
    tenant_id: MOCK_TENANT_ID,
    bank_goal_id: 'goal-006',
    audit_objective_id: 'obj-006',
    relevance_score: 1.0,
    rationale: 'Sürdürülebilir finansman hedefi ile ESG uyum denetimi doğrudan ilişkilidir.',
    created_at: '2026-01-07T15:15:00Z',
    updated_at: '2026-01-07T15:15:00Z',
  },
  {
    id: 'align-007',
    tenant_id: MOCK_TENANT_ID,
    bank_goal_id: 'goal-001',
    audit_objective_id: 'obj-003',
    relevance_score: 0.80,
    rationale: 'Dijital büyüme için siber güvenlik altyapısının sağlamlığı temel gereksinimdir.',
    created_at: '2026-01-07T15:30:00Z',
    updated_at: '2026-01-07T15:30:00Z',
  },
  {
    id: 'align-008',
    tenant_id: MOCK_TENANT_ID,
    bank_goal_id: 'goal-002',
    audit_objective_id: 'obj-007',
    relevance_score: 0.75,
    rationale: 'Operasyonel verimlilik için iç kontrol sistemlerinin optimize edilmesi destekleyici faktördür.',
    created_at: '2026-01-07T15:45:00Z',
    updated_at: '2026-01-07T15:45:00Z',
  },
  {
    id: 'align-009',
    tenant_id: MOCK_TENANT_ID,
    bank_goal_id: 'goal-003',
    audit_objective_id: 'obj-001',
    relevance_score: 0.70,
    rationale: 'Siber güvenlik güçlendirme için dijital altyapının bütüncül değerlendirilmesi faydalıdır.',
    created_at: '2026-01-07T16:00:00Z',
    updated_at: '2026-01-07T16:00:00Z',
  },
];

export const mockStrategyData = {
  bankGoals: MOCK_BANK_GOALS,
  auditObjectives: MOCK_AUDIT_OBJECTIVES,
  alignments: MOCK_ALIGNMENTS,
};

export const MOCK_STRATEGIC_GOALS = [
  {
    id: '1',
    title: 'Pazar Payını %15 Artırma',
    description: 'KOBİ segmentinde agresif büyüme.',
    progress: 65,
    riskAppetite: 'High' as const,
    linkedAuditObjectives: ['101', '102']
  },
  {
    id: '2',
    title: 'Operasyonel Verimlilik',
    description: 'Maliyet/Gelir rasyosunu düşürme.',
    progress: 40,
    riskAppetite: 'Medium' as const,
    linkedAuditObjectives: ['103']
  },
  {
    id: '3',
    title: 'Sıfır Mevzuat İhlali',
    description: 'BDDK ve MASAK uyumu.',
    progress: 90,
    riskAppetite: 'Low' as const,
    linkedAuditObjectives: ['104']
  }
];

export const MOCK_AUDIT_OBJECTIVES_SIMPLE = [
  { id: '101', title: 'Kredi Tahsis Süreç Denetimi', type: 'Assurance' as const, status: 'On Track' as const },
  { id: '102', title: 'Yeni Müşteri Kazanım Riskleri', type: 'Advisory' as const, status: 'At Risk' as const },
  { id: '103', title: 'Şube Operasyonları Optimizasyonu', type: 'Advisory' as const, status: 'On Track' as const },
  { id: '104', title: 'AML/KYC Süreç Denetimi', type: 'Assurance' as const, status: 'On Track' as const }
];
